sudo: false

language: node_js
node_js:
- "node"

matrix:
  include:
    - os: linux
    - os: osx

services:
- xvfb

install:
- npm install
- npm run build

script:
- npm test
- npm run ui-test
- npm run coverage:upload